implemented homework
mmmmmcr/newsReader pull request #1
Opened 2021-05-27 15:01 UTC by mmmmmcr

Am lasat pe constructorul din ArticleItemViewModel link-ul hardcodat ca sa nu il mai pun de fiecare data in mock pe constructor.

2021-06-22 20:52 UTC, mmmmmcr commented
check first variant

2021-07-05 12:38 UTC, Misca commented on data/src/main/java/com/example/data/repo/NewsRepositoryImpl.java
> +    RemoteSource source;
we could pe making these fields private and final, also let's have same naming (remoteDataStore, localDataStore )

2021-07-05 12:40 UTC, Misca requested changes
almost there 👍

2021-07-05 12:40 UTC, Misca commented on data/src/main/java/com/example/data/repo/remote/RemoteSource.java
> +    NewsAPI newsAPI;
let's hane the newsAPI final and private

2021-07-05 12:40 UTC, Misca commented on data/src/main/java/com/example/data/repo/remote/RemoteSource.java
> +public class RemoteSource {
let's rename this class, our local class is called NewsLocalDataStore, for consistency let's rename this one to NewsRemoteDataStore (naming conventions are part of an architecture)

2021-07-07 10:54 UTC, Misca approved these changes
GG 👍

2021-07-07 10:54 UTC, merged